services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    command: bun dev --host
    ports:
      - 3000:5173
    develop:
      watch:
        - path: web/package.json
          action: rebuild
        - path: web/bun.lockb
          action: rebuild
        - path: web/
          target: /app
          action: sync
          ignore:
            - node_modules

  api:
    build: ./api
    command: bun --watch index.ts
    ports:
      - 4000:4000
    develop:
      watch:
        - path: api/
          target: /app
          action: sync
          ignore:
            - node_modules
