services:
  web:
    build: ./web
    volumes:
      - ./web:/app

  api:
    build: ./api
    command: bun --watch index.ts
    ports:
      - 4000:4000
    volumes:
      - ./api:/app

  nginx:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
      - api
